/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/fox_in_a_cape.glb 
Author: SkylarFox.VR (https://sketchfab.com/bonfire.png)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/fox-in-a-cape-1b061329af8746b79267f56852b17204
Title: Fox in a cape
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'


export function Fox(props) {
  const { scene } = useGLTF(`${import.meta.env.BASE_URL}models/fox_in_a_cape.glb`, 'https://www.gstatic.com/draco/v1/decoders/')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.5}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.material} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.material} skeleton={nodes.Object_9.skeleton} />
            <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.material} skeleton={nodes.Object_11.skeleton} />
            <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.material} skeleton={nodes.Object_13.skeleton} />
            <skinnedMesh geometry={nodes.Object_48.geometry} material={materials.material} skeleton={nodes.Object_48.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/fox_in_a_cape.glb`, 'https://www.gstatic.com/draco/v1/decoders/')
